# This file is automatically @generated by Poetry 2.2.1 and should not be changed by hand.
package = []

[metadata]
lock-version = "2.1"
python-versions = ">=3.13"
content-hash = "43c15d4b40e26b9dc4090308565270876da3b72ef2b9fa0bddbe4b344cfe177c"
